const adminActions = { LOGIN_ADMIN_ACTION: "LOGIN_ADMIN_ACTION" };

const layoutActions = {
  SET_LOADING_ACTION: "SET_LOADING_ACTION",
  SET_LOCALE_ACTION: "SET_LOCALE_ACTION",
  SET_DROP_DOWN_ELEMENT_ACTION: "SET_DROP_DOWN_ELEMENT_ACTION",
  SET_SHOWN_MODAL_ACTION: "SET_SHOWN_MODAL_ACTION",
};

const messageActions = {
  SET_MESSAGE_ACTION: "SET_MESSAGE_ACTION",
  SET_RENDER_MESSAGE_ACTION: "SET_RENDER_MESSAGE_ACTION",
  CLEAR_MESSAGE_ACTION: "CLEAR_MESSAGE_ACTION",
};

const pageActions = {
  CHANGE_PAGE_ACTION: "CHANGE_PAGE_ACTION",
  SET_PAGE_PROPS_ACTION: "SET_PAGE_PROPS_ACTION",
};

export { adminActions, layoutActions, messageActions, pageActions };
